[package]
name = "niri-waybar"
version = "0.3.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
async-channel = "2.5.0"
niri-ipc = "25.8.0"
serde = { version = "1.0.228", features = ["derive"] }
waybar-cffi = "0.1.1"

[lib]
name = "niri_waybar"
crate-type = ["cdylib"]
